### ISSUE TITLE
Group capstone: set up Kanban board 

### ISSUE THREAD

**Issue by MozamelJawad** [AliRezaBmeDu/javascript-capstone#21]
**In this activity, we prepare a Kanban board with a GitHub project.**

In this group, we are two members:
- Student-A: @AliRezaBmeDu 
- Student-B @MozamelJawad 

The following is the link to our GitHub project:  [GitHub project](https://github.com/AliRezaBmeDu/javascript-capstone/projects/1)

**Comment by TedLivist** [comment]
## STATUS: CHANGES REQUIRED ♻️ ♻️

Hi @MozamelJawad and @AliRezaBmeDu,

Good job so far!
✔️ Kanban columns are complete
✔️ Tasks are complete
However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [ ] Kindly ensure all your tasks are assigned according to Students A and B. The group tasks can have multiple assignees.

  ![andre-assigned](https://github.com/AliRezaBmeDu/javascript-capstone/assets/36542986/319529a5-947e-4d8a-b83c-f11e2411d877)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Issue for re-reviews. You should use the same Issue submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
